# default: &default
#   adapter: sqlite3
#   database: ":memory:" 

# development:
#   <<: *default

# test:
#   <<: *default

production:
  adapter: sqlite3
  database: ":memory:"

cable:
  adapter: sqlite3
  database: ":memory:"

queue:
  adapter: sqlite3
  database: ":memory:"

cache:
  adapter: sqlite3
  database: ":memory:"
